services:
  auth_ms:
    container_name: auth_ms
    build:
      context: .
    command: 
      ["sh", "docker/app.sh"]
    env_file:
      - .env
    depends_on:
      - postgresql

  postgresql:
    container_name: psql_auth_ms
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-0420}
      POSTGRES_DB: auth
    ports:
      - "5440:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/db-init:/docker-entrypoint-initdb.d
volumes:
  postgres-data: