"""empty message

Revision ID: 54c57190b4b7
Revises: 14cab0f82e81
Create Date: 2024-11-12 01:34:59.877045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c57190b4b7'
down_revision: Union[str, None] = '14cab0f82e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_session', sa.Column('session_num', sa.Integer(), nullable=False))
    op.create_unique_constraint('user_session_unique', 'user_session', ['user_id', 'session_num'])
    op.create_unique_constraint(None, 'user_session', ['refresh_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_session', type_='unique')
    op.drop_constraint('user_session_unique', 'user_session', type_='unique')
    op.drop_column('user_session', 'session_num')
    # ### end Alembic commands ###
