"""empty message

Revision ID: 7ae71356b32e
Revises: 54c57190b4b7
Create Date: 2024-11-29 18:34:36.514049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae71356b32e'
down_revision: Union[str, None] = '54c57190b4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('user_session', 'fingerprint_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=False,
               postgresql_using='fingerprint_hash::bytea')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_session', 'fingerprint_hash',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
