"""empty message

Revision ID: 14cab0f82e81
Revises: a68fe3399615
Create Date: 2024-11-11 09:35:41.085040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14cab0f82e81'
down_revision: Union[str, None] = 'a68fe3399615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_session_refresh_token_key', 'user_session', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_session_refresh_token_key', 'user_session', ['refresh_token'])
    # ### end Alembic commands ###
